name: Tests

on:
  push:
    branches: [ "master", "development" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: curl
        ini-values: memory_limit=-1, date.timezone='Europe/Warsaw'
        coverage: xdebug
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run codeception
      env:
        TEST_API_URI: ${{ secrets.TEST_API_URI }}
        TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
      run: vendor/bin/codecept run

    - name: Run phpstan
      run: vendor/bin/phpstan analyse --no-progress --xdebug